### ISSUE TITLE
Implement short URL's for long (and messy) wall URL's

### ISSUE THREAD

**Issue by aneeshd16** [fossasia/loklak_webclient#107]
Wall URL's will be long and tamper prone: ` /wall/display?eventName=abcd&mainHashtag=loklak...`
This feature will create a unique ID for that URL and store it in the backend. Loklak server already has provisions for storing arbitrary data using the `apps` object.

For eg:
`/wall/display?id=some_id` will redirect to `/wall/display?eventName=abcd&mainHashtag=loklak...`
We can also have something like wall/display/some_ID

**Comment by Orbiter** [comment]
wouldn't be a loklak_server-internal link shortener be a good solution for that? I believe a link shortener within loklak was on the list what we wanted to do.
@mariobehling whats your suggestion?

**Comment by mariobehling** [comment]
Well, a link shortener and short system ID-Links are two different things for me. A link shortener can always be implemented. A loklak_server-internal link shortener - what would be necessary for that? Can it be used for other things as well?

**Comment by Orbiter** [comment]
I believe we discovered that we need a link shortener if we provide to tweet from loklak. Links attached in our own links must be shortened to b usable for the users. Therefore a shortener service is obligatory. When we discussed the point, you said that we then also should have our own shortener.

**Comment by mariobehling** [comment]
@Orbiter What is the priority on that? I would add that to M3. We need to find a suitable short domain.

**Comment by Orbiter** [comment]
this has low priority since we can apply this later, even after GSoC just by changing server processes. But meanwhile everyone has to use an explicit shortener, like bit.ly or use the raw url.
