### ISSUE TITLE
Page showing followers and following for the user after being logged in.

### ISSUE THREAD

**Issue by sudheesh001** [fossasia/loklak_webclient#248]
Implementation after : https://github.com/loklak/loklak_server/issues/61

Once loklak would be able to scrape the followers and following information of the user, we should be able to show case the list of followers and people whom you follow on loklak too.

It'll look similar to https://twitter.com/<user_handle>/followers and https://twitter.com/<user_handle>/following

**Comment by mariobehling** [comment]
Looking at this issue, it seems to be related to accounts, settings and less to the "loklak tweets" project. So I am assigning this issue to @aneeshd16

**Comment by aneeshd16** [comment]
Seems to be a part of #283

**Comment by mariobehling** [comment]
Just compare to https://twitter.com/following and https://twitter.com/followers
The question is how do we deal with this. We should probably give users in future the possibility to follow each other within loklak, but we can display followers/following from twitter for now on loklak.net/following or /followers and later add a section of loklak internal followers above that.

**Comment by Orbiter** [comment]
please retrieve the follower list from loklak_server, documentation is online at http://loklak.org/api.html#account .. please scroll down to "Retrieval of Twitter User Account Data" for details
