### ISSUE TITLE
Popular Walls Deck

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_webclient#273]
Add a deck item "Popular Walls" to the test.loklak.net/walls

**Comment by aneeshd16** [comment]
For popular walls, i was thinking of using the hashtags from the "trends" feature that @sudheesh001 is currently implementing. These walls will have some fixed settings, and will be editable (for the current session). We can have a `#loklak` wall permanently at the top.

**Comment by mariobehling** [comment]
@Orbiter What are your ideas to show popular walls in the walls area? How to achieve this?
