### ISSUE TITLE
Create User Profile Page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_webclient#283]
What is on that page?
1. Compare to twitter
2. A view of the user data on a map

What is the URL?
http://loklak.net/-ashorturl 
for a unique username people could pay.

This is related to accounts and twitter wall account implementation issues and UI https://github.com/loklak/loklak_webclient/issues/227

**Comment by aneeshd16** [comment]
Can we move this to M3? I need more time for user acc mgmt and wall dashboard.

**Comment by mariobehling** [comment]
done.
