### ISSUE TITLE
Ensure all followers are displayed on loklak map correctly

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_webclient#309]
There are lots of followers of me who entered Berlin as a location. However, only two show up. Also Tweepsmap shows that 17.1% of my followers are in Berlin.

* Tweepsmap
![screenshot from 2015-07-07 15 35 25](https://cloud.githubusercontent.com/assets/1583873/8547246/d3d68656-24bd-11e5-8e2a-8db36b86295f.png)

* Loklak: Only two followers
![screenshot from 2015-07-07 15 37 00](https://cloud.githubusercontent.com/assets/1583873/8547271/16016fdc-24be-11e5-8c04-f46e697a19eb.png)

**Comment by prasht63** [comment]
@mariobehling Sometimes a bad response comes from the Twitter side through hello.js.That is causing this.I will implement a statistics visualiser with Issue #296 . It should clear things up for the viewer. So moving it to #296

**Comment by mariobehling** [comment]
@Orbiter suggested, that accounts might be displayed above each other and therefore do not show up. It is possible to implement an algorithm to display accounts in a circle.

**Comment by mariobehling** [comment]
Also see here https://github.com/loklak/loklak_webclient/issues/278

**Comment by Orbiter** [comment]
The retrieval of followers from the twitter client inside loklak_webclient should be replaced by a retrieval of those data from loklak_server. Therefore I re-open this issue: please retrieve the follower list from loklak_server, documentation is online at http://loklak.org/api.html#account .. please scroll down to "Retrieval of Twitter User Account Data" for details.
