### ISSUE TITLE
Implement a followers/following map with percentage view according to location in /map and search

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_webclient#311]
An example of a similar feature is tweepsmap.

![screenshot from 2015-07-07 16 22 27](https://cloud.githubusercontent.com/assets/1583873/8548331/814fe272-24c4-11e5-874b-d707e4aff1b0.png)

**Comment by Orbiter** [comment]
please retrieve the follower list from loklak_server, documentation is online at http://loklak.org/api.html#account .. please scroll down to "Retrieval of Twitter User Account Data" for details

**Comment by mariobehling** [comment]
To clarify, this should go to loklak.net/map as an option for the map.

![screenshot from 2015-08-04 12 52 46](https://cloud.githubusercontent.com/assets/1583873/9059251/9579de84-3aa8-11e5-94fb-3bb0805f4ab7.png)

**Comment by prasht63** [comment]
@mariobehling The map you see in analyze https://github.com/loklak/loklak_webclient/pull/429#issue-98835173 is not actually a map but a geochart.Its not possible to integrate it with maps as an overlay since leaflet does not support that.

**Comment by mariobehling** [comment]
@prasht63 It does not make sense not to be able to display this info on our standard map. We do not need an UI that works differently on each page and follows different concepts. 

The solution would be to identify the relevant technology that can help us to get this feature.

**Comment by prasht63** [comment]
I am looking for someway through which this can be done.
