### ISSUE TITLE
Card Layout for wall

### ISSUE THREAD

**Issue by aneeshd16** [fossasia/loklak_webclient#319]
Tracker for all card related issues:

#304

I am currently using https://github.com/akoenig/angular-deckgrid for a fixed width layout.

Will post updates here.

**Comment by mariobehling** [comment]
As there are a number of related issues and design items I moving this to M3 now as an ongoing issue.

**Comment by aneeshd16** [comment]
@Orbiter 
>See example:
<img width="1003" alt="toomuchspace" src="https://cloud.githubusercontent.com/assets/238730/8544880/65f709da-24a9-11e5-9811-a753f30acf66.png">
Why is there so much space wasted? Is this a placeholder for something else (i.e. other media)?

**Comment by aneeshd16** [comment]
Test link for new wall card layout: http://aneesh-ojl02abl.cloudapp.net/aneeshd16/wall/VJRDSK_c

**Comment by mariobehling** [comment]
Let's bring this closer to tweetwall's design:
* [ ] move user photo to button area
* [ ] increase size of tweet font
* [ ] show photos in larger size and add twitter text in smaller size below or on the side (Let's see what makes more sense)
* [ ] decrease size of gray are between tweet tiles

**Comment by aneeshd16** [comment]
Card layout update: http://aneesh-ojl02abl.cloudapp.net/aneeshd16/wall/VJRDSK_c
![image](https://cloud.githubusercontent.com/assets/5436027/9230126/3448f22a-413e-11e5-9a51-2acc85918cfe.png)

**Comment by aneeshd16** [comment]
There are 3 possible widths:
* If the tweet contains an image, card is `col-xs-6`.
* If not then
    * If tweet text > 70 characters, card is `col-xs-4`
    * else card is `col-xs-3`

**Comment by aneeshd16** [comment]
Currently, layout gets messed up if leaderboard is enabled

**Comment by aneeshd16** [comment]
Updated, variable size images do not waste space any more
http://aneesh-ojl02abl.cloudapp.net/aneeshd16/wall/VJRDSK_c
![](https://files.gitter.im/loklak/zKFw/blob)

**Comment by mariobehling** [comment]
Would be great also to avoid empty areas on the right of the screen. I think adding new decks on the left and then moving them to the right as discussed before could be nice.
