### ISSUE TITLE
Use loklak as a basis to show activity stream on home and map view - just like in the search

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_webclient#405]
Differences are for example the way pictures are shown. Data queried from loklak generates the original picture.

What is required to do this?
-> show tweets of following

Compare tweet shown in home view
![screenshot from 2015-07-30 16 27 37](https://cloud.githubusercontent.com/assets/1583873/8985548/3ea7f7ea-36d8-11e5-8820-0908a3db94ca.png)

and map view
![screenshot from 2015-07-30 16 27 14](https://cloud.githubusercontent.com/assets/1583873/8985556/45774ddc-36d8-11e5-88c7-b38e413cfa92.png)

with same tweet view of search

![screenshot from 2015-07-30 16 26 24](https://cloud.githubusercontent.com/assets/1583873/8985557/45bee8b8-36d8-11e5-83aa-a32783c9c5ae.png)

**Comment by fuksi** [comment]
Currently data from Home view and Map feeds comes from Twitter API (through Hello.js). This kind of data is not supported yet on loklak. https://github.com/loklak/loklak_server/issues/94

However, I can also show pictures in map feeds as well. I'll try to abstract the implementation, so when the feature is supported from the server, this can be easily modified.

**Comment by fuksi** [comment]
Done in the Pr above.

**Comment by mariobehling** [comment]
Thank you for the update! 

This is still using the Twitter-Api though, correct? Therefore I do not regard this as solved and move this to 4.5.
