### ISSUE TITLE
when searching for "from:<user>" show a user profile page

### ISSUE THREAD

**Issue by Orbiter** [fossasia/loklak_webclient#411]
If you see a search result and click on a users image, you now get a search page for the user, like
http://test.loklak.net/search?q=from:katemueser which is good. This should correspond to the user profile page of that user like https://twitter.com/katemueser.

We need such a page with all that information of the user on the page because we don't have otherwise a place to put a "FOLLOW" button on. This feature is a preparation for that next step.

To do:
- check if the search page contains the query `from:<user>`
- if the page does only contain that query, you have identified the `<user>`. Then show this like the user's profile page view

IMPORTANT: *just re-use existing code for the home view* and *make an abstraction of that code* DON'T do a copy-paste of the home view code.

![screenshot from 2015-08-02 13 43 17](https://cloud.githubusercontent.com/assets/1583873/9025972/79d6e088-391c-11e5-8a3a-5e43959aa7c1.png)

**Comment by Orbiter** [comment]
To see where this is leading: feature https://github.com/loklak/loklak_webclient/issues/412 will add a 'Follow' - button on that page. It is therefore important that the page is compsed of components where it is easy to add content (the button) inside the page.

**Comment by fuksi** [comment]
First version is implemented with the PR above. 

Additional features those can be implemented in MS 4.5
- The search result contains data from other sources. Separate those other sources than twitter. Show in sidebar is there is any (create some logic to balance the layout)
- Following/Followers tab can also be created
- Disable (grey out, not hide) temporarily Favorites & Lists tabs until further support.
