### ISSUE TITLE
Loklak Widgets Ideas and Implementation

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_webclient#433]
What widgets can be implemented with the data we collect in loklak? Please add more ideas.

User related
* [ ] country wise followers
* [ ] region wise followers
* [ ] city wise followers
* [ ] followers distribution (percentage wise distribution of followers)
* [ ] most influential followers/following (with the most followers)
* [ ] language wise distribution of followers

Trends
* [ ] trends of a user based on a hashtag
* [ ] trends among followers/following
* [ ] location trends (regional, national, global)
* [ ] trends in different languages

Tweets Analysis
* [ ] date and time distribution of tweets, e.g. month view
* [ ] top tweeter of a certain hashtag
* [ ] most influential tweeter of a certain hashtag
* [ ] top user mentions with a certain hashtag
* [ ] top related hashtags with a main hashtag

Search Terms
* [ ] most influential tweeters of results of a search (with the most followers)
* [ ] top tweeters within a search result
* [ ] language wise distribution of accounts of a given search result (city, region, national)
* [ ] location wise distribution of accounts of a given search result
* [ ] trends/top hashtags among tweeters of a given search result
* [ ] top user mentions of a given search result

**Comment by Orbiter** [comment]
I don't understand the trends completely. What does it show?

To produce the necessary startistics, there are two servlets
- the /api/user.json: the front-end must evaluate (count!) the properties from the result set themself
- the /api/search.json: the aggregations for the statistics are provided by elasticsearch, use the 'fields' attributes as described in the api doc for "Search Result Aggregations".

Things that I would like to have is: a 'large view' for single analysis functions. Like the 'most influential followers' which currently only shows the top-X (x=3?). I would like to see a complete list.

**Comment by mariobehling** [comment]
Trends: Twitter shows top hashtags and regular words in tweets of all or of a regional group of users. With the data in loklak we could also generate that information for a single user.
![screenshot from 2015-08-05 17 03 30](https://cloud.githubusercontent.com/assets/1583873/9089207/437b6296-3b94-11e5-949a-41f8feb5f725.png)

**Comment by mariobehling** [comment]
> large view
We can always implement a view "more" link, that creates an overlay lightbox with more items.
In this issue here, I would like to understand if there are more widgets that would be interesting and possible with the loklak data set.
