### ISSUE TITLE
Improve layout of Wall List View

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_webclient#455]
* [ ] Increase size of photos to use complete height of available area

![screenshot from 2015-08-11 17 07 04](https://cloud.githubusercontent.com/assets/1583873/9201331/c323cce2-404c-11e5-8965-672b6be83619.png)

* [x] get rid of line breaks in tweets
* [x] adjust tweet design to match photo size on left
* [x] avoid overlap of tweet content with account info
* [x] decrease unused space between short tweets and account info
* [x] add "ago" after time information on bottom

![screenshot from 2015-08-11 17 08 13](https://cloud.githubusercontent.com/assets/1583873/9201457/7f05b60a-404d-11e5-80f1-3f666dff648f.png)

**Comment by aneeshd16** [comment]
![image](https://cloud.githubusercontent.com/assets/5436027/9474691/cb2e82cc-4b7f-11e5-9c31-1ece75d36873.png)

**Comment by mariobehling** [comment]
The issue above comes up when there is a photo. I do not see, that you test with a photo.

**Comment by aneeshd16** [comment]
Posted a wrong screen grab, this should make more sense

![image](https://cloud.githubusercontent.com/assets/5436027/9475007/a311e39a-4b81-11e5-961a-6e90a3489f8c.png)
With CSS Borders to check alignment
![image](https://cloud.githubusercontent.com/assets/5436027/9475024/b687fbd0-4b81-11e5-84b9-cf056c21aaea.png)

**Comment by mariobehling** [comment]
So, if it does not come up when there is a leaderboard, it looks good to me.

**Comment by mariobehling** [comment]
Regarding the leaderboard, I am still thinking the proportions. Before we had two fields on top that provided information. Now we have a rather empty area on the right. There would be different options to improve the space usage: 
Either: Cycle Top Twitterers and Top Mentions on the left and keep Top Hashtags on the right
Or: Reduce the leaderboard sidebar in size e.g. 20% or similar
What is your idea?
![screenshot from 2015-08-25 23 38 24](https://cloud.githubusercontent.com/assets/1583873/9480429/4957c4b2-4b83-11e5-819a-8e9affe152c9.png)
