### ISSUE TITLE
Report: User photos in banner are scaled wrongly

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_webclient#495]
Please compare the user account photo in loklak and twitter e.g. in the home banner or account search. The height/width are distorted. Please fix this.

Loklak
![screenshot from 2015-08-19 10 26 52](https://cloud.githubusercontent.com/assets/1583873/9351833/d433e236-465c-11e5-866b-4664c36415ba.png)

Twitter
![screenshot from 2015-08-19 10 23 13](https://cloud.githubusercontent.com/assets/1583873/9351820/bc801aa6-465c-11e5-9964-7eec351a8ebe.png)

**Comment by sudheesh001** [comment]
### Accounts View
Before
<img width="314" alt="screen shot 2015-08-19 at 4 56 26 pm" src="https://cloud.githubusercontent.com/assets/4545925/9355070/45a52250-4693-11e5-8a91-26d619bab576.png">
After
<img width="303" alt="screen shot 2015-08-19 at 4 56 42 pm" src="https://cloud.githubusercontent.com/assets/4545925/9355072/483b6cae-4693-11e5-9fd4-ba8fc3cd17fd.png">
Note the quality of the image.

**Comment by mariobehling** [comment]
Ok, please also compare this: Some user photos are displayed "stretched together", meaning people appear thinner.

**Comment by sudheesh001** [comment]
@mariobehling The accounts and other areas with bad image quality is changed, is there still an issue in this ?

**Comment by mariobehling** [comment]
Please deploy and we will test in detail.

**Comment by sudheesh001** [comment]
@mariobehling Any update ?

**Comment by mariobehling** [comment]
It looks like in loklak account photos are not scaled wrongly and made into a square even though the base image is not a square. The result: The photo on loklak make the user image stretch/squeezed together. See the image below, the user photo makes the user appear thinner than in reality.

Twitter
![screenshot from 2015-08-21 23 29 40](https://cloud.githubusercontent.com/assets/1583873/9419506/891b0282-485c-11e5-96d7-0a3e427c0f22.png)

Loklak
![screenshot from 2015-08-21 23 28 57](https://cloud.githubusercontent.com/assets/1583873/9419511/911fc1de-485c-11e5-8632-318740f7fc6b.png)

**Comment by mariobehling** [comment]
![screenshot from 2015-08-26 09 39 45](https://cloud.githubusercontent.com/assets/1583873/9487942/6f80625e-4bd6-11e5-8160-c98b92db7b24.png)

Design is out of order, overlaps and is not a square anymore.

**Comment by mariobehling** [comment]
Please compare to twitter. Such a pity you do not realize this yourself.

**Comment by sudheesh001** [comment]
Plrease refer https://github.com/loklak/loklak_webclient/pull/517#issuecomment-134920731
