### ISSUE TITLE
User information un viewedable when at top of map

### ISSUE THREAD

**Issue by smokingwheels** [fossasia/loklak_webclient#536]
When clicking a dot on the map towards the top of the information is cut off or behind menu.

![user cut off on map](https://cloud.githubusercontent.com/assets/11748913/9974939/8873d80a-5edb-11e5-9a4f-cebaf932e8a6.JPG)

**Comment by sopu** [comment]
I believe this problem can be fixed if the pop-ups which overlap with the menu are opened downwards rather than upward. 
Working on it!

**Comment by sopu** [comment]
One solution could be to start the map below the menu. @aneeshd16 @sudheesh001 suggestions?

**Comment by aneeshd16** [comment]
If we start the map below the menu, that will not solve this problem. If a user clicks somewhere far in the north (greenland etc), the popup will still not be visible, right?

**Comment by sopu** [comment]
As far as I understand, when the leaflet is going out of bounds, the map is shifted downward to incorporate the pop-up. 
I will put up a PR for it using this approach. Please see if it solves the issue.
