### ISSUE TITLE
Creating a loklak wall redirects to /wall/undefined

### ISSUE THREAD

**Issue by sudheesh001** [fossasia/loklak_webclient#539]
Previous walls created are also not available.

**Comment by smokingwheels** [comment]
Also I had random Tweets show up in my wall and thats when I closed the iframe to a link.

**Comment by aneeshd16** [comment]
@sudheesh001 Could you please re check? I tried it 5 min back and could not reproduce this error. Also try a cache clear. There were some updates recently.

**Comment by SilentFlame** [comment]
@sudheesh001 anyone working on this?
I would like to give it a try.

**Comment by sudheesh001** [comment]
@SilentFlame Please go ahead and give it a try :smile:

**Comment by SilentFlame** [comment]
@sudheesh001  can you please guide me as to where should I look to understand this issue.
As I'm going through the codes, your help would be great to get a grip. :)
