### ISSUE TITLE
Wall creation UI date picker right and left arrows missing

### ISSUE THREAD

**Issue by markspolakovs** [fossasia/loklak_webclient#558]
![As shown in this screenshot](https://cloud.githubusercontent.com/assets/2904440/12490196/a0f14a98-c074-11e5-88f9-afb2e188e642.PNG)The left and right arrow icons in the date picker UI are not showing up. I'm using Chrome 47 on Windows 10, User-Agent string `"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36"`.

**Comment by aneeshd16** [comment]
![image](https://cloud.githubusercontent.com/assets/5436027/12872201/e83e2efc-cdc1-11e5-883b-2ceae0914274.png)

@marksomnian Should be fixed via #563
