### ISSUE TITLE
loklak.net and www.loklak.net though are the same hit a CORS error while creating walls

### ISSUE THREAD

**Issue by sudheesh001** [fossasia/loklak_webclient#593]
The walls only work on loklak.net and not with www.loklak.net they'll forever load, Would it be possible to redirect all traffic from www.loklak.net => loklak.net from the DNS settings ?

**Comment by treba123** [comment]
Or probably just in nginx

**Comment by sudheesh001** [comment]
```shell
server {
    server_name www.loklak.net;
    rewrite ^/(.*)$ http://loklak.net/$1 permanent;
}
```
Should be enough for a 301 redirect from www to non-www, What do you think @treba123 @Orbiter
