### ISSUE TITLE
User account management

### ISSUE THREAD

**Issue by aneeshd16** [fossasia/loklak_webclient#74]
* Implement authentication (from #38)

**Comment by mariobehling** [comment]
This seems to be overlapping with #102 and #103 
What is the progress here?

**Comment by mariobehling** [comment]
I am renaming this issue. @aneeshd16 Can you help please and implement the account feature in regards to all of loklak instead of only the wall?

**Comment by aneeshd16** [comment]
Yes, will do. Currently only the wall needs to store user data. The access to storage functions on loklak_server will be via the node server (oauth-proxy). I will develop a system that will allow other apps to store arbitrary data on loklak_server. Support for this already exists server side.

**Comment by mariobehling** [comment]
Ok, moving this to M2.5 then.

**Comment by mariobehling** [comment]
Thoughts on accounts:
* user should be able to login with email address
* user gets an account link generated by system e.g. loklak.net/sdigf2dsf98sj
* user can add an account name of his choice e.g. loklak.net/favouriteusername, but we will charge 1 USD per year for this (let's use Paypal for the beginning)
 * how to implement this? Think of how Facebook allows people to register their page. You are on hold to have your own page short name until you have 20 likes
 * An advantage will also be that we have less fake accounts and unused accounts like Twitter
 * verification of users can be done through mobile phone (check out Twilio-Api)

**Comment by aneeshd16** [comment]
@mariobehling, This would require a lot of support from loklak_server. OR we can implement all that logic in our node server. We need to discuss this in detail.

My thoughts:
* User should be able to log in with both twitter and email id. In case the user logs in with twitter, we will ask for the email id if we are unable to get it from twitter.
* Can we auto-generate the account link based on the twitter id? For eg, I would automatically get loklak.net/aneeshd16. For email users, we can give them a random string.
* Any user on twitter will automatically have a loklak page. twitter.com/abcd will have loklak.net/abcd. However, we don't need to store all these details from the start. loklak.net/abcd will be generated dynamically (using Twitter API) when someone visits that URL. It will be a public page, and will have something like a "Claim account" link which will direct the user to log in using twitter. Once the user logs in, we can start storing that user's data.
* Regarding resource usage, we can have four levels of users:
  * Unclaimed accounts
  * Claimed accounts (user has logged into loklak via twitter)
  * Verified accounts (user has verified mobile no, via Twilio)
  * Paid accounts (user has paid to use the service)
* Depending on the level, we can implement different types of rate limitation on the users. Paid accounts will have no limits, verified accounts will have a few limits, and so on.


However, this issue is dealing with just the storage and retrieval of user data in loklak_server, which has been solved in https://github.com/loklak/loklak_webclient/commit/b8461e531f99a4632d7980f97f0b1dc0c07e2ccf and will be in the next PR.

**Comment by mariobehling** [comment]
> Can we auto-generate the account link based on the twitter id?

Twitter is just one service. We should also support login with Facebook. In this logic we should then generate a URL with the FB account. Also, people should be able to create their own ID without Twitter soon.

> Any user on twitter will automatically have a loklak page. twitter.com/abcd

Twitter is the starting point for loklak and not the only reference. Why should we limit users to the account names of twitter? There are many unused accounts on twitter as well. We are an independent service. At the moment the home page of users looks similar to twitter. We will start to change that step by step. We need to think more about this. Maybe the twitter data of users can stay at loklak.net/t/abcd?

> loklak.net/abcd will be generated dynamically (using Twitter API) when someone visits that URL. 

Ok, I get this point. We need to think about it. One thing: We cannot depend too much on the twitter-API. The amount of data we can download through the API is limited. So any page generation should be going through loklak asap.

> we can have four levels of users

I am not entirely sure, what "levels" incorporates, but yes, we need a permission system and automatic roles upgrades when a user performs an action. There were also questions about users with additional permissions e.g. organization admin accounts (think of admins of pages in FB), or users with admin rights, who could fix things in accounts. 

Should we have a UI for defining all this? Let's start step by step.

**Comment by aneeshd16** [comment]
Agree on  your thoughts about being an independent service on not relying too much on Twitter.

> >loklak.net/abcd will be generated dynamically (using Twitter API) when someone visits that URL.

> Ok, I get this point. We need to think about it. One thing: We cannot depend too much on the twitter-API. The amount of data we can download through the API is limited. So any page generation should be going through loklak asap.

Sure, loklak already has basic user details, so we can easily display that page using loklak instead of twitter. This would be done when #283 is complete anyway.

> we need a permission system and automatic roles upgrades when a user performs an action. There were also questions about users with additional permissions e.g. organization admin accounts (think of admins of pages in FB), or users with admin rights, who could fix things in accounts.

At the very basic stage, we can have a badge for each user which will be that user's role. If we want to support admin accounts, then admin accounts should also have a list of accounts which it can administrate. (Something like an ACL).

We should also think in terms of the technology available to us. We can either add full blown accounts support in loklak_server or leverage our existing node server to store all this. 
@Orbiter @sudheesh001 @fuksi @prasht63

**Comment by mariobehling** [comment]
@aneeshd16 The question is also if and how we differentiate between user's role and products? E.g. a user gets different additional wall features. What are your ideas?

**Comment by aneeshd16** [comment]
Moving to M3 as its an ongoing discussion.

**Comment by Orbiter** [comment]
@mariobehling what user accounts shall be valid in the future wall? loklak.net should have it's own wall managment now, but how is an user authenticated? Only twitter or also other methods?
